### ISSUE TITLE
MUP AWS Beanstalk + Sentry using zodern:standard-minifier-js

### ISSUE THREAD

**Issue by emaciel10** [zodern/mup-aws-beanstalk#48]
We are looking to get access to production source maps in Sentry so that we can more easily debug those errors. Does anyone know of a reliable way to upload sourcemaps to sentry on each deploy to elastic beanstalk? 

Right now I am considering writing a post deploy script that will create a new release and upload the source maps to sentry manually using either sentry-cli or sentry api but I am not sure if any existing integration already exists.

Thanks!

**Comment by zodern** [comment]
There isn't any existing integration I know of.

Using a post deploy script, a [hook](http://meteor-up.com/docs.html#hooks), or creating a [Mup plugin](http://meteor-up.com/plugins.html) would work.

The bundle is in a temp folder with a random name, using the app's path as the seed. If the app and mup config is always at the same location when deploying, you could hard code the bundle path. Otherwise you can copy the code from [here](https://github.com/zodern/mup-aws-beanstalk/blob/master/src/utils.js#L24).
